#!/bin/bash
cd $HOME
mkdir $1 >&- 2>&-
for param in "$@"
do
	if [ "$param" != "$1" -a "$param" != "$2" ]
	then
		files = find -name "*$param"
		for file in files
		do
			cp file $1
		done
	fi
done

tar -cf "$2".tar "$1"

echo "done"

