#!/bin/bash
cd $HOME
mkdir $1 >&- 2>&-
for param in "$@"
do
	if [ "$param" != "$1" -a "$param" != "$2" ]
	then
		find -name "*$param" >&- 2>&- -exec cp '{}' $1 \;
	fi
done

tar -cf "$2".tar "$1"

echo "done"

